// File generated by Firebase Setup Script.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_app_base/flavors.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns true if Firebase has been configured with real credentials.
  /// Returns false if still using placeholder values.
  static bool get isConfigured {
    try {
      final options = currentPlatformForFlavor;
      return !options.apiKey.startsWith('{{');
    } catch (e) {
      return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get currentPlatformForFlavor {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }

    // Check if we're in staging flavor using F.appFlavor
    final isStaging = F.appFlavor == Flavor.staging;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isStaging ? androidStaging : androidProduction;
      case TargetPlatform.iOS:
        return isStaging ? iosStaging : iosProduction;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidProduction = FirebaseOptions(
    apiKey: '{{ANDROID_PRODUCTION_API_KEY}}',
    appId: '{{ANDROID_PRODUCTION_APP_ID}}',
    messagingSenderId: '{{ANDROID_PRODUCTION_MESSAGING_SENDER_ID}}',
    projectId: '{{ANDROID_PRODUCTION_PROJECT_ID}}',
    storageBucket: '{{ANDROID_PRODUCTION_STORAGE_BUCKET}}',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: '{{ANDROID_STAGING_API_KEY}}',
    appId: '{{ANDROID_STAGING_APP_ID}}',
    messagingSenderId: '{{ANDROID_STAGING_MESSAGING_SENDER_ID}}',
    projectId: '{{ANDROID_STAGING_PROJECT_ID}}',
    storageBucket: '{{ANDROID_STAGING_STORAGE_BUCKET}}',
  );

  static const FirebaseOptions iosProduction = FirebaseOptions(
    apiKey: '{{IOS_PRODUCTION_API_KEY}}',
    appId: '{{IOS_PRODUCTION_APP_ID}}',
    messagingSenderId: '{{IOS_PRODUCTION_MESSAGING_SENDER_ID}}',
    projectId: '{{IOS_PRODUCTION_PROJECT_ID}}',
    storageBucket: '{{IOS_PRODUCTION_STORAGE_BUCKET}}',
    iosClientId: '{{IOS_PRODUCTION_CLIENT_ID}}',
    iosBundleId: '{{IOS_PRODUCTION_BUNDLE_ID}}',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: '{{IOS_STAGING_API_KEY}}',
    appId: '{{IOS_STAGING_APP_ID}}',
    messagingSenderId: '{{IOS_STAGING_MESSAGING_SENDER_ID}}',
    projectId: '{{IOS_STAGING_PROJECT_ID}}',
    storageBucket: '{{IOS_STAGING_STORAGE_BUCKET}}',
    iosClientId: '{{IOS_STAGING_CLIENT_ID}}',
    iosBundleId: '{{IOS_STAGING_BUNDLE_ID}}',
  );

  // Legacy options for backward compatibility
  static FirebaseOptions get android => androidProduction;
  static FirebaseOptions get ios => iosProduction;
}
