import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:tacit_mobile/bloc/config_bloc.dart';
import 'package:tacit_mobile/screens/home_screen.dart';
import 'package:tacit_mobile/mixins/navigation.dart';

/// Scans a QR code generated by TACIT's connect.sh.
///
/// Expected format: tacit://<base64url-encoded JSON>
/// Decoded JSON: {"url": "http://192.168.1.137:8642", "key": "abc123"}
class QrScanScreen extends StatefulWidget {
  const QrScanScreen({super.key});

  @override
  State<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends State<QrScanScreen> with Navigation {
  final MobileScannerController _controller = MobileScannerController();
  bool _processed = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_processed) return;

    for (final barcode in capture.barcodes) {
      final raw = barcode.rawValue;
      if (raw == null || !raw.startsWith('tacit://')) continue;

      _processed = true;
      await _controller.stop();

      try {
        final encoded = raw.substring('tacit://'.length);
        final decoded = utf8.decode(base64Url.decode(base64Url.normalize(encoded)));
        final data = jsonDecode(decoded) as Map<String, dynamic>;

        final url = data['url'] as String? ?? '';
        final key = data['key'] as String? ?? '';

        if (url.isEmpty) {
          _showError('QR code missing server URL.');
          _processed = false;
          await _controller.start();
          return;
        }

        await ConfigBloc().setServerConfig(serverUrl: url, apiKey: key);

        if (mounted) {
          popAllAndPush(const HomeScreen());
        }
      } catch (e) {
        _showError('Invalid QR code format.');
        _processed = false;
        await _controller.start();
      }

      return;
    }
  }

  void _showError(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: Colors.red),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan TACIT QR Code'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Stack(
        children: [
          MobileScanner(
            controller: _controller,
            onDetect: _onDetect,
          ),
          Positioned(
            bottom: 48,
            left: 24,
            right: 24,
            child: Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text(
                  'Point your camera at the QR code shown by\n./connect.sh on the LLM Mac.',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.grey[600]),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
