name: Production iOS Deployment

on:
  workflow_dispatch:

jobs:
  production_ios:
    uses: ./.github/workflows/ios.yml
    secrets: inherit
    with:
      pilot_apple_id: ${{ vars.PILOT_APPLE_ID }}
      flavor: production