name: Production Android Firebase Deployment

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/android.yml
    secrets: inherit
    with:
      flavor: production
      platform: android_firebase
      supply_package_name: dev.twinsun.flutter_app_base